#!/usr/bin/env python3


import pickle
import numpy as np

def cv( vals ):
    return np.std( vals )/np.mean( vals )



mm = pickle.load(open('mult_mapper.pickle','rb'))

good = 0

for vv in mm.values():
    g1, g2 = vv[0:10], vv[10:]
    good += (cv(g1)<0.20)and(cv(g2)<0.20)


print( good )
